apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdh_app1-helm.fullname" . }}
  labels:
    {{- include "hdh_app1-helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hdh_app1-helm.selectorLabels" . | nindent 4 }}
