apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-java-helm.fullname" . }}
  labels:
    {{- include "demo-java-helm.labels" . | nindent 4 }}
    app: dso-demo-java
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-java-helm.selectorLabels" . | nindent 6 }}
      app: dso-demo-java
  template:
    metadata:
      labels:
        {{- include "demo-java-helm.selectorLabels" . | nindent 8 }}
        app: dso-demo-java
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PG_SERVICE
              value: {{ .Values.postgresql.fullnameOverride }}
            - name: PG_DATABASE
              value: {{ .Values.global.postgresql.auth.database }}
            - name: PG_USER
              value: {{ .Values.global.postgresql.auth.username }}
            - name: PG_PASSWORD
              value: {{ .Values.global.postgresql.auth.password }}
            - name: SPRING_DATASOURCE_USERNAME
              value: $(PG_USER)
            - name: SPRING_DATASOURCE_PASSWORD
              value: $(PG_PASSWORD)
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://$(PG_SERVICE):5432/$(PG_DATABASE)
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}